In [22]:
import torch 
import numpy as np

In [23]:
np.random.seed(42)
nl = 5
ls = [np.random.randint(1,10) for i in range(l)]
ns = [np.random.randint(1,10) for i in range(l)]
n = 4
d = 3

In [106]:
torch.zeros((0,1))

tensor([], size=(0, 1))

In [110]:
[*range(5)][-1]

4

In [115]:
len(torch.Tensor())

0

In [59]:


class dotdict(dict):
    """dot.notation access to dictionary attributes"""
    __getattr__ = dict.__getitem__
    __setattr__ = dict.__setitem__
    __delattr__ = dict.__delitem__



In [26]:
v0, w0 = [], []
for i in range(nl):
    v0.append(torch.zeros(ls[i], ls[i]))
    w0.append(torch.zeros(ns[i], ns[i]))    
V0 = torch.kron(torch.zeros(n,n), torch.block_diag(*v0))
W0 = torch.kron(torch.zeros(n,n), torch.block_diag(*w0))
Qp = torch.block_diag(V0, W0)

In [37]:
v0 = (torch.zeros(ls[i], ls[i]) for i in range(nl))
[*v0]

[tensor([[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]]),
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]]),
 tensor([[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]),
 tensor([[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 

In [48]:
torch.linalg.svd(torch.eye(10))

torch.return_types.linalg_svd(
U=tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]]),
S=tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
Vh=tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0

In [58]:
dict().get('P')

In [60]:
M = dotdict()
a = M.P

KeyError: 'P'

In [72]:
float('inf')

inf

In [73]:
n = 5
nx = 3
torch.kron(torch.diag(torch.ones(n-1), 1), torch.eye(nx))

tensor([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0.,

In [41]:
torch.cat(list(torch.zeros(1, 1) for i in range(5)))

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.]])

In [33]:
sum(ls) * n
sum(ns) * n
W0.shape

torch.Size([108, 108])

In [77]:
m = np.zeros(2)
m[:] = W0.shape
m

array([108., 108.])

In [103]:
def block_matrix(nested_lists): 
    # a is a list of list [[[], [], tensor], [[], tensor, []]]
    # row and column size must be similar
    sizes = np.zeros((len(nested_lists), len(nested_lists[0]), 2))
    for i, row in enumerate(nested_lists): 
        for j, e in enumerate(row): 
            sizes[i, j, :] = e.shape if len(e) > 0 else (0, 0)
    row_sizes = sizes.max(1)[:, 0].astype(int)
    col_sizes = sizes.max(0)[:, 1].astype(int)
    
    arr = []
    for i, row in enumerate(nested_lists): 
        arr_row = []
        for j, e in enumerate(row): 
            if len(e) > 0: 
                arr_row.append(e)
            else: 
                arr_row.append(np.zeros((row_sizes[i], col_sizes[j])))
        print([_.shape for _ in arr_row])
        arr.append(np.concatenate(arr_row, axis=1))
    return np.concatenate(arr, axis=0)

In [105]:
torch.tensor(block_matrix([[[], np.eye(3), []], 
              [np.ones((4, 2)), [], np.ones((4,1))]]))

[(3, 2), (3, 3), (3, 1)]
[(4, 2), (4, 3), (4, 1)]


tensor([[0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [1., 1., 0., 0., 0., 1.],
        [1., 1., 0., 0., 0., 1.],
        [1., 1., 0., 0., 0., 1.],
        [1., 1., 0., 0., 0., 1.]], dtype=torch.float64)

In [ ]:
 def to_generalized_coordinates(self, series): 
        """ series: torch tensor (n_batchs, n_times, dim) 
            inspired from spm_DEM_embed.m
            series_generalized = T * [series[t-order/2], dots, series[t+order/2]]
        """
        n_batchs, n_times, dim = series.shape
        p = self._order

        E = torch.zeros((p + 1, p + 1))
        times = torch.arange(n_times)

        # Create E_ij(t) (note that indices start at 0) 
        for i in range(p + 1): 
            for j in range(p + 1): 
                E[i, j] = (i + 1 - int((p + 1) / 2))**(j) / np.math.factorial(j) 

        # Compute T
        T = torch.linalg.inv(E)

        # Compute the slices
        slices = []
        for t in times: 
            start = int(t - (p + 1) / 2)
            end = start + p + 1
            if start < 0: 
                slices.append(slice(0, p + 1))
            elif end > n_times:
                slices.append(slice(n_times - (p + 1), n_times))
            else: 
                slices.append(slice(start, end))

        series_slices = torch.stack([series[:, _slice] for _slice in slices], dim=1)

        # series_slices is (n_batchs, n_times, order + 1, dim)
        # T is ( order+1, order+1)
        generalized_coordinates = torch.einsum('ijkl,mk->ijlm', series_slices, T)


        return generalized_coordinates